services:
  - type: web
    name: fastconnect-internet
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        value: fastconnectinternet-peterjumaodhiambo254-53b8.c.aivencloud.com
      - key: DB_PORT
        value: 20748
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_11CiDbAHCIeyGz66Mp3
      - key: DB_NAME
        value: defaultdb